### ISSUE TITLE
Player goals and fears

### ISSUE THREAD

**Issue by didehvar** [codeninjasclub/guild-masters#1]
See the [trello card](https://trello.com/c/zTS48QTi/10-implement-a-character-data-structure) for more details.

> Goal: Objective that when accomplished increases happiness and/or attributes and/or may give a positive trait.

> Fear: Event that when accomplished decreases happiness and/or attributes and/or may give a negative trait.

Waiting on the implementation of some kind of event manager as goals and fears will really on conditions being met. Not really super important for now, anyway.

**Comment by GeraintCorneu** [comment]
Resolved in the following commits:
* Commit https://github.com/codeninjasclub/guild-masters/commit/bddbb58a51b66e90d7ba6e5ff267c1d1564e7a30 
* Commit https://github.com/codeninjasclub/guild-masters/commit/98a2186faa57b4b80bcd9a97d26132dc2c8b691b

**Example**
*Custom Event*
```java
public class GoalMetEvent extends AbstractEvent{
    private Goal goal;

    public GoalMetEvent() {
         super(GoalMetEvent.class.getSimpleName());
    }

    public Goal getGoal() { return this.goal; }

    public void setGoal(Goal goal) { this.goal = goal; }
}
```
*Register Event and Action*
```java
public class Character extends UpdateableEntity {
    public Goal goal;
    public Character(String name) {
        super(name);

        this.setAction(new GoalMetEvent(), (trigger) -> {
                if (((GoalMetEvent) trigger).getGoal().equals(this.goal)) {
                    // Do whatever you want to do when a goal is met.
                }      
            })    
    }
}
```
